Controllers/PersonellerController.cs
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SerpApi;
using System.Collections;
using System.Diagnostics;
using System.Text;
using TaramaMVC.Helper;
using TaramaMVC.Models;

namespace TaramaMVC.Controllers
{
    //[Authorize]
    public class PersonellerController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly IConfiguration _configuration;
        //private static IWebDriver _driver=null;
        public PersonellerController(DatabaseContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;

        }

        // GET: Personeller
        ////[Authorize]
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.Personels.OrderByDescending(t => t.Alintilanma).Include(p => p.AnaBilimDallari);

            return View(await databaseContext.ToListAsync());
        }
        public async Task<IActionResult> FindIndex()
        {
            var databaseContext = _context.Personels.OrderByDescending(t => t.Alintilanma).Include(p => p.AnaBilimDallari);

            return View(await databaseContext.ToListAsync());
        }

        // GET: Personeller/Details/5
        ////[Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Personels == null)
            {
                return NotFound();
            }

            var personel = await _context.Personels
                .Include(p => p.AnaBilimDallari)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personel == null)
            {
                return NotFound();
            }

            return View(personel);
        }




        // GET: Personeller/Create
        ////[Authorize]
        public IActionResult Create()
        {
            ViewData["PersonelId"] = new SelectList(_context.Personels, "Id", "Name");
            ViewData["AnaBilimDallariId"] = new SelectList(_context.AnaBilimDals, "Id", "Name");
            return View();
        }

        // POST: Personeller/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        ////[Authorize]
        public async Task<IActionResult> Create([Bind("Id,Name,SurName,AnaBilimDallariId,ScholarName,User")] Personel personel)
        {
            try
            {
                personel.User = personel.Name + " " + personel.SurName;
            }
            catch (Exception ex)
            {

                personel.User = "yok";
            }

            if (ModelState.IsValid)
            {
                //personel.Name = personel.Name;

                _context.Add(personel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnaBilimDallariId"] = new SelectList(_context.AnaBilimDals, "Id", "Name", personel.AnaBilimDallariId);
            return View(personel);
        }

        // GET: Personeller/Edit/5
        ////[Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Personels == null)
            {
                return NotFound();
            }

            var personel = await _context.Personels.FindAsync(id);
            if (personel == null)
            {
                return NotFound();
            }
            personel.AnaBilimDallari = _context.AnaBilimDals.Find(personel.AnaBilimDallariId);
            ViewData["AnaBilimDallariId"] = new SelectList(_context.AnaBilimDals, "Id", "Name", personel.AnaBilimDallariId);
            return View(personel);
            //return RedirectToAction(nameof(Index));
        }

        // POST: Personeller/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        ////[Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,SurName,AnaBilimDallariId,ScholarName,User")] Personel personel)
        {
            if (id != personel.Id)
            {
                return NotFound();
            }
            if (personel.AnaBilimDallariId > 0)
            {
                var anabilims = await _context.AnaBilimDals.FindAsync(personel.AnaBilimDallariId);
                personel.AnaBilimDallari = anabilims;
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personel);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonelExists(personel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }
            ViewData["AnaBilimDallariId"] = new SelectList(_context.AnaBilimDals, "Id", "Name", personel.AnaBilimDallariId);
            return View(personel);
        }

        //alıntı güncelle
        ////[Authorize]
        public async Task<IActionResult> AGuncelle(int? id)
        {


            YayinAlintiBilgisi yAB = null;
            /**/
            HtmlDocument doc = null;
            /**/
            var Pyb = await _context.PersonelYayinBilgileris.Where(r => r.Alinti > 0 && r.PersonelId == id).ToListAsync();
            if (Pyb != null && Pyb.Count > 0)
            {
                foreach (var pyb in Pyb)
                {
                    //Alinti Getir

                    HtmlWeb web = new HtmlWeb();
                    web.UseCookies = true;
                    web.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36";

                    //doc = web.Load(pyb.BaslikCites, "get");
                    //TaramaMVC.Helper.Helperim.GetPage(pyb.BaslikCites);
                    doc = TaramaMVC.Helper.Helperim.GetPage(pyb.BaslikCites);
                    List<YayinAlintiBilgisi> liste = new List<YayinAlintiBilgisi>();


                    // var liste = Helperim.AlintiGetir(pyb.BaslikCites);//, ylo,yhi);
                    if (liste != null && liste.Count > 0)
                    {
                        foreach (var item in liste)
                        {
                            yAB = null;
                            yAB = new YayinAlintiBilgisi();
                            yAB.personelYayinBilgileriId = pyb.Id;
                            //yAB.Ad = item;
                            await _context.YayinAlintiBilgisis.AddAsync(yAB);
                        }
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        // return Content(doc.Text, System.Net.Mime.MediaTypeNames.Text.Html, Encoding.GetEncoding("iso-8859-9"));
                    }

                }
                return Content(doc.Text, System.Net.Mime.MediaTypeNames.Text.Html, Encoding.GetEncoding("iso-8859-9"));

            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Personeller/Delete/5 AGuncelle 
        ////[Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Personels == null)
            {
                return NotFound();
            }

            var personel = await _context.Personels
                .Include(p => p.AnaBilimDallari)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personel == null)
            {
                return NotFound();
            }
            // ViewData["AnaBilimDallariId"] = new SelectList(_context.AnaBilimDals, "Id", "Name", personel.AnaBilimDallariId);
            return View(personel);
        }

        // POST: Personeller/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        ////[Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Personels == null)
            {
                return Problem("Entity set 'DatabaseContext.Personels'  is null.");
            }
            var personel = await _context.Personels.FindAsync(id);
            if (personel != null)
            {
                _context.Personels.Remove(personel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonelExists(int id)
        {
            return _context.Personels.Any(e => e.Id == id);
        }
        ////[Authorize] AlintiVerileriSil
        public async Task<IActionResult> AlintiVerileriSil()
        {
            string mesaj = "";
            try
            {

                var silinecekler2 = await _context.YayinAlintiBilgisis.ToListAsync();

                _context.YayinAlintiBilgisis.RemoveRange(silinecekler2);

                await _context.SaveChangesAsync();
                MessageModel mm = new MessageModel();
                mm.Durum = true;
                mm.Baslik = "Alıntı Verileri Silme İşlemi";
                mm.Acıklama = "Alıntı Verileri Silindi. İşlem tamam.";
                return View("Message", mm);
            }
            catch (Exception ex)
            {

                mesaj = "Hata : " + ex.Message;
            }

Views/Personeller/Create.cshtml
@model TaramaMVC.Models.Personel

@{
    ViewData["Title"] = "Akademik Personel Ekleme";
}

<div class="container-sm">
    <h1 class="bg-info text-white">AKADEMIK PERSONEL EKLE</h1>

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group md-2 mt-2">
            <label asp-for="Name" class="control-label text-secondary  m-lg-3 bg-light">Adı</label>
                <input asp-for="Name" class="form-control" placeholder="Name" />
                
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group md-2 mt-2">
            <label asp-for="SurName" class="control-label text-secondary  m-lg-3 bg-light">Soyadı</label>
             <input asp-for="SurName" class="form-control" placeholder="Soyadı" />
             <span asp-validation-for="SurName" class="text-danger"></span>
         </div>
            
            <div class="form-group md-2 mt-2">
            <label asp-for="AnaBilimDallariId" class="control-label text-secondary m-lg-3 bg-light">Ana Bilim Dallari</label>
                <select asp-for="AnaBilimDallariId" class="form-control" asp-items="ViewBag.AnaBilimDallariId" placeholder="AnaBilimDalı"></select>
            </div>
           <div class="form-group md-2 mt-2">
            <label asp-for="ScholarName" class="control-label text-secondary m-lg-3 bg-light">Google Scholar Name</label>
            <input asp-for="ScholarName" class="form-control" placeholder="Scholar Name" />
            <span asp-validation-for="ScholarName" class="text-danger"></span>
            </div>
        <div class="form-group md-2 mt-2">
            <label asp-for="User" class="control-label text-secondary m-lg-3 bg-light">Google Scholar User ID</label>
            <input asp-for="User" class="form-control" placeholder="User ID" />
            <span asp-validation-for="User" class="text-danger"></span>
        </div>
            <div class="row">
                <div class="col form-group md-2 mt-2">
                    @* <input type="submit" value="Create" class="btn btn-secondary" />*@
                    <button type="submit" class="form-control btn-secondary">
                        <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#save1" /></svg>
                        Kaydet
                    </button>
                </div>
            </div>
         
        </form>
        <div class="row">
            <div class="col form-group md-2 mt-2">
                <a asp-action="Index" class="form-control btn btn-secondary">
                    <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#back1" /></svg>
                    Geri
                </a>
            </div>
        </div>
    
</div>

@*<div class="row">
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Personeller/Delete.cshtml
@model TaramaMVC.Models.Personel

@{
    ViewData["Title"] = "Akademik Personel Sil Mesajı";
}

<div class="container-sm">
    <h3 class="bg-warning text-dark">Silmek istediğinize emin misiniz ?</h3>

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurName)
        </dd>
        <dt class = "col-sm-2">
            @Html.Label("AnaBilimDallari")
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnaBilimDallari.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.Label("Google Scholar Name")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ScholarName)
        </dd>
        <dt class="col-sm-2">
            @Html.Label("Google Scholar User ID")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="row">
            <div class="col form-group md-2 mt-2">
                <input type="submit" value="Delete" class="form-control btn btn-danger" />
            </div>
        </div>
        <div class="row">
            <div class="col form-group md-2 mt-2">
                <a asp-action="Index" class="form-control btn btn-secondary">
                    <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#back1" /></svg>
                    Geri
                </a>
            </div>
        </div>
    </form>

</div>

Views/Personeller/Details.cshtml
@model TaramaMVC.Models.Personel

@{
    ViewData["Title"] = "Akademik Personel Detayları";
}

<div class="container">
 
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AnaBilimDallari)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnaBilimDallari.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ScholarName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ScholarName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
   
    </dl>

<div class="row">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-secondary" >Düzenle</a> |
    <a asp-action="Index" class="btn btn-secondary" >Geri Dön</a>
</div>
</div>

Views/Personeller/Edit.cshtml
@model TaramaMVC.Models.Personel

@{
    ViewData["Title"] = "Akademik Personel Güncelleme";
}
<div class="container">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group md-2 mt-2">
             @*   <label asp-for="Name" class="control-label"></label>*@
                <input asp-for="Name" class="form-control" placeholder="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group md-2 mt-2">
               @* <label asp-for="SurName" class="control-label"></label>*@
                <input asp-for="SurName" class="form-control" placeholder="SurName" />
                <span asp-validation-for="SurName" class="text-danger"></span>
            </div>
            <div class="form-group md-2 mt-2">
                @*<label asp-for="AnaBilimDallariId" class="control-label"></label>*@
                <select asp-for="AnaBilimDallariId" class="form-control" asp-items="ViewBag.AnaBilimDallariId" placeholder="AnaBilimDalı"></select>
                <span asp-validation-for="AnaBilimDallariId" class="text-danger"></span>
            </div>
            <div class="form-group md-2 mt-2">
                @* <label asp-for="SurName" class="control-label"></label>*@
                <input asp-for="ScholarName" class="form-control" placeholder="ScholarName" />
                <span asp-validation-for="ScholarName" class="text-danger"></span>
            </div>
            <div class="form-group md-2 mt-2">
                @* <label asp-for="SurName" class="control-label"></label>*@
                <input asp-for="User" class="form-control" placeholder="User ID" />
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
             
                    <div class="Row md-2 mt-2">
                    <button type="submit" class="form-control btn-secondary">
                        <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#save1" /></svg>
                        Kaydet
                    </button>
                </div>
             
        </form>
            <div class="Row md-2 mt-2">
                <a asp-action="Index" class="form-control btn btn-secondary md-2 mt-2">
                    <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#back1" /></svg>
                    Geri
                </a>
            </div>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
@foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
{
    <div>@error.ErrorMessage</div>
}

Views/Personeller/Index.cshtml
@model IEnumerable<TaramaMVC.Models.Personel>

@{
    //Layout = "~/Views/Shared/_Layout_x.cshtml";
    ViewData["Title"] = "Akademik Personeller";
    int RowNo = 0;

}

<div class="container-sm">
    <div class="row">

        <div class="col-6 text-md-start">
            <h2 class="text-primary">  <svg class="bi me-2 mx-auto mb-1" width="16" height="16"><use xlink:href="#person" /></svg> @ViewData["Title"] </h2>
        </div>
    @if (User?.Identity?.IsAuthenticated ?? false)
    {

       
           <div class="col-6 text-md-end">
                        <a class="btn btn-warning" asp-area="" asp-controller="Personeller" asp-action="VeriGuncelle">
                    <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#download" /></svg>
                    
                    Yayınları Getir</a>
               
                <a class="btn btn-danger" asp-area="" asp-controller="Personeller" asp-action="VerileriSil">
                    <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#delete1" /></svg>
                    Yayınları Sil</a>
                      
                <a class="btn btn-danger" asp-area="" asp-controller="Personeller" asp-action="AlintiVerileriSil">
                    <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#delete2" /></svg>
                    Alıntıları Sil</a>
                     
                <a asp-action="Create" class="btn btn-primary ">
                        <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#create1" /></svg>
                    Yeni Akademisyen
                </a>
                </div>
       
    
    }
        </div>    <hr />
<div class="row">
      
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-sm table-bordered table-hover table-striped table-dashboard data-table" id="tblliste">
                        <thead>
                            <tr>
                                <th>
                                    @Html.Label("SıraNo")
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.SurName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.AnaBilimDallari)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ScholarName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.User)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Alintilanma)
                                </th>
                            <th>
                                @Html.DisplayNameFor(model => model.h_endex)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.i10_endex)
                            </th>
                                @* <th>
                                @Html.DisplayNameFor(model => model.ApiKey)
                                </th>*@
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @{
                                            RowNo++;
                                        } @RowNo
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SurName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AnaBilimDallari.Name)
                                    </td>
                                    <td>
                                        <a title="https://scholar.google.com/citations?hl=tr&view_op=search_authors&mauthors=@item.ScholarName" href="https://scholar.google.com/citations?hl=tr&user=@item.User" target="_blank">@Html.DisplayFor(modelItem => item.ScholarName)</a>
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.User)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Alintilanma)
                                    </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.h_endex)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.i10_endex)
                                </td>
                                    @* <td>
                                @if(item.ApiKey.Length>0)
                                {
                                @Html.Label("Var")
                                }else

                                {
                                @Html.Label("Yok")
                                }
                                </td>*@
                                    <td>
                                        <div class="btn-group btn-group-sm btn-block">


                                            @if (User?.Identity?.IsAuthenticated ?? false)
                                            {
                                                @if (item.Alintilanma > 0)
                                                {
                                                    <div class="btn-sm">
                                                        <a asp-action="AlintiGuncelleYeniEski" asp-route-id="@item.Id" class="btn-sm btn btn-block">
                                                            <svg class="bi d-block mx-auto mb-0" width="16" height="16"><use xlink:href="#quote" /></svg>Update
                                                        </a>
                                                    </div>

                                                    <div class="btn-sm">
                                                        <a asp-action="AlintiGuncelleApi" asp-route-id="@item.Id" class="btn-sm btn btn-block">
                                                            <svg class="bi d-block mx-auto mb-0" width="16" height="16"><use xlink:href="#quote" /></svg>UpdateApi
                                                        </a>
                                                    </div>
                                                }
                                                @* <div class="btn-sm">
                                        <a asp-action="Details" asp-route-id="@item.Id" class="btn-sm btn btn-block">
                                        <svg class="bi d-block mx-auto mb-0" width="16" height="16"><use xlink:href="#view1" /></svg>İncele
                                        </a>
                                        </div>*@
                                                <div class="btn-sm">
                                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn-sm btn btn-block">
                                                        <svg class="bi d-block mx-auto mb-0" width="16" height="16"><use xlink:href="#edit1" /></svg>Düzenle
                                                    </a>
                                                </div>

                                                <div class="btn-sm">
                                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn-sm btn btn-block">
                                                        <svg class="bi d-block mx-auto mb-0" width="16" height="16"><use xlink:href="#delete1" /></svg>Sil
                                                    </a>
                                                </div>
                                            }
                                            else
                                            {
                                                @*      <div class="btn-sm">
                                        <a asp-action="Details" asp-route-id="@item.Id" class="btn-sm btn btn-block">
                                        <svg class="bi d-block mx-auto mb-0" width="16" height="16"><use xlink:href="#view1" /></svg>İncele
                                        </a>
                                        </div>*@
                                            }


                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>

    </div>

    
</div>



<script type="text/javascript" >
    $(document).ready(function () {
             
            var table = $('#tblliste').DataTable({
            responsive: true,
            dom: 'Bfrtip',
            lengthMenu: [
                [25, 50, 100, -1],
                ['İlk 25', 'İlk 50', 'İlk 100', 'Hepsi']
            ],
            buttons: [
                'pageLength',
                'excel',
                'pdf' 
                
            ]
            
        });
       

            table.buttons().container()
                .appendTo($('.col-4', table.table().container()));
                                    });

     
</script>

Views/Personeller/Message.cshtml
@model TaramaMVC.Models.MessageModel

@{
    ViewData["Title"] = Model.Baslik;

}

<div class="container-sm">
    <h3 class="bg-light text-secondary">@Model.Acıklama </h3>

    <div class="col form-group md-2 mt-2">
        <a asp-action="Index" class="form-control btn btn-secondary">
            <svg class="bi d-block mx-auto mb-1" width="16" height="16"><use xlink:href="#back1" /></svg>
            Geri
        </a>
    </div>
</div>